language: java

jdk: oraclejdk8

sudo: false # faster builds

script: "mvn install"

before_deploy:
  - "mvn -DskipTests package"
  
deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key:
      secure: 874ac6fac01d1e61c9fe67025eb2f8df663b6046
    file: /home/travis/build/namila007/Maze-Solver/target/Maze-Solver-1.0-SNAPSHOT.jar
    skip_cleanup: true
    on:
      tags:
    all_branches: true
    on_success: always
    on_failure: never  
